version: "3.8"

services:
  app:
    build: ../..
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1qaz2wsx
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example_db
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

